apiVersion: v1
kind: Pod
metadata:
  name: windows-server-allowed-capabilities-win
  labels:
    app: windows-server-allowed-capabilities-win
spec:
  nodeSelector:
    kubernetes.io/os: windows
  containers:
  - name: windows-server
    image: mcr.microsoft.com/windows/servercore:ltsc2019
    command:
      - "powershell.exe"
      - "-command"
    args:
      - "Start-Sleep -s 1000"
    securityContext:
      capabilities:
        add: ["disallowedcapability"]