apiVersion: v1
kind: Pod
metadata:
  name: nginx-apparmor-violation
  annotations:
    apparmor.security.beta.kubernetes.io/pod: unconfined
    container.apparmor.security.beta.kubernetes.io/container-exclude: unconfined
  labels:
    app: nginx-apparmor-violation
spec:
  nodeSelector:
    kubernetes.io/os: linux
  containers:
  - name: container-exclude
    image: mcr.microsoft.com/oss/nginx/nginx:1.17.3-alpine
  - name: except-image
    image: exception.azurecr.io/exception:1.0.0
