apiVersion: v1
kind: Pod
metadata:
  name: nginx-apparmor
  annotations:
    # Assuming policy applied with allowedProfiles including 'runtime/default'
    apparmor.security.beta.kubernetes.io/pod: runtime/default
    container.apparmor.security.beta.kubernetes.io/nginx: runtime/default
  labels:
    app: nginx-apparmor
spec:
  nodeSelector:
    kubernetes.io/os: linux
  containers:
  - name: nginx
    image: mcr.microsoft.com/oss/nginx/nginx:1.17.3-alpine
  - name: nginx2
    image: mcr.microsoft.com/oss/nginx/nginx:1.17.3-alpine
