apiVersion: v1
kind: Pod
metadata:
  name: violation-nodeclare
  labels:
    app: violation-nodeclare
spec:
  containers:
  - name: nginx
    image: mcr.microsoft.com/oss/nginx/nginx:1.17.3-alpine
---
apiVersion: v1
kind: Service
metadata:
  name: nodeclare-service
spec:
  ports:
  - port: 8080
