apiVersion: v1
kind: Pod
metadata:
  name: default-pod
  namespace: default
  labels:
    app: default-pod
spec:
  containers:
  - name: nginx
    image: mcr.microsoft.com/oss/nginx/nginx:1.17.3-alpine
---
apiVersion: v1
kind: Service
metadata:
  name: default-service
  namespace: default
spec:
  ports:
  - port: 8080
