apiVersion: v1
kind: Pod
metadata:
  name: nginx-users-violation
  labels:
    app: nginx-users-violation
spec:
  nodeSelector:
    kubernetes.io/os: linux
  securityContext:
    supplementalGroups:
      - 50
    fsGroup: 50
  containers:
    - name: nginx
      image: mcr.microsoft.com/oss/nginx/nginx:1.17.3-alpine
      securityContext:
        runAsUser: 50
        runAsGroup: 50
      resources:
        limits:
          cpu: "100m"
          memory: "30Mi"
