apiVersion: v1
kind: Pod
metadata:
  name: nginx-forbidden-sysctls
  labels:
    app: nginx-forbidden-sysctls
spec:
  nodeSelector:
    kubernetes.io/os: linux
  containers:
  - name: nginx
    image: mcr.microsoft.com/oss/nginx/nginx:1.17.3-alpine
    resources:
      limits:
        cpu: "100m"
        memory: "30Mi"
  securityContext:
    sysctls:
    - name: net.ipv4.ip_local_port_range
      value: "65536"
