apiVersion: v1
kind: Pod
metadata:
  name: violateimage
  labels:
    app: container-allowed-images
spec:
  nodeSelector:
    kubernetes.io/os: linux
  containers:
  - name: nginx
    image: gcr.io/google-samples/node-hello:1.0
    ports:
    - containerPort: 8080