apiVersion: v1
kind: Pod
metadata:
  name: nginx-uid-violation
  labels:
    app: nginx-uid-violation
spec:
  nodeSelector:
    kubernetes.io/os: linux
  containers:
  - name: nginx
    image: mcr.microsoft.com/oss/nginx/nginx:1.17.3-alpine
    securityContext:
      runAsUser: 200