apiVersion: v1
kind: Pod
metadata:
  name: nginx-readonlyrootfilesystem-exclude
  labels:
    app: nginx-readonlyrootfilesystem-exclude
spec:
  nodeSelector:
    kubernetes.io/os: linux
  containers:
  - name: container-exclude
    image: mcr.microsoft.com/oss/nginx/nginx:1.17.3-alpine
    securityContext:
      readOnlyRootFilesystem: false
    resources:
      limits:
        cpu: "100m"
        memory: "30Mi"
  - name: except-image
    image: exception.azurecr.io/exception:1.0.0
    securityContext:
      readOnlyRootFilesystem: false
