apiVersion: v1
kind: Pod
metadata:
  name: nginx-readonlyrootfilesystem
  labels:
    app: nginx-readonlyrootfilesystem
spec:
  nodeSelector:
    kubernetes.io/os: linux
  containers:
  - name: nginx
    image: mcr.microsoft.com/oss/nginx/nginx:1.17.3-alpine
    securityContext:
      readOnlyRootFilesystem: true
    resources:
      limits:
        cpu: "100m"
        memory: "30Mi"
