apiVersion: v1
kind: Pod
metadata:
  name: nginx-proc-mount-violation-exclusion
  labels:
    app: nginx-proc-mount-violation-exclusion
spec:
  nodeSelector:
    kubernetes.io/os: linux
  containers:
  - name: container-exclude
    image: mcr.microsoft.com/oss/nginx/nginx:1.17.3-alpine
    securityContext:
      procMount: Unmasked
  - name: except-image
    image: exception.azurecr.io/exception:1.0.0
    securityContext:
      procMount: Unmasked
