apiVersion: v1
kind: Pod
metadata:
  name: nginx-host-filesystem-exclude
  labels:
    app: nginx-host-filesystem-exclude
spec:
  nodeSelector:
    kubernetes.io/os: linux
  containers:
  - name: container-exclude
    image: mcr.microsoft.com/oss/nginx/nginx:1.17.3-alpine
    volumeMounts:
    - mountPath: /cache
      name: cache-volume
      readOnly: false
    resources:
      limits:
        cpu: "100m"
        memory: "30Mi"
  - name: image-exemption
    image: exception.azurecr.io/exception:v1.0
    volumeMounts:
    - mountPath: /tmp
      name: disallowed-volume
  volumes:
  - name: cache-volume
    hostPath:
      path: /etc # directory location on host
  - name: disallowed-volume
    hostPath:
      path: /tmp
