apiVersion: v1
kind: Pod
metadata:
  name: violatelatest
  labels:
    app: container-allowed-images
spec:
  nodeSelector:
    kubernetes.io/os: linux
  containers:
  - name: nginx
    image: mcr.microsoft.com/oss/nginx/nginx:latest # pullPolicy will be set Always, referring to https://kubernetes.io/docs/concepts/containers/images/#imagepullpolicy-defaulting