apiVersion: v1
kind: Service
metadata:
  name: load-balancer-violation
spec:
  selector:
    app: MyApp
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 9375
  clusterIP: 10.96.0.2
  type: LoadBalancer
