apiVersion: v1
kind: Pod
metadata:
  name: nginx-allowed-probes
  labels:
    app: nginx-allowed-probes
spec:
  nodeSelector:
    kubernetes.io/os: linux
  containers:
  - name: container1
    image: mcr.microsoft.com/oss/nginx/nginx:1.17.3-alpine
    readinessProbe:
      tcpSocket:
        port: 8080
      initialDelaySeconds: 5
      periodSeconds: 10
    livenessProbe:
      httpGet:
        path: /healthz
        port: 8080
        httpHeaders:
        - name: Custom-Header
          value: Awesome
      initialDelaySeconds: 3
      periodSeconds: 3
  - name: exclude-container
    image: mcr.microsoft.com/oss/nginx/nginx:1.17.3-alpine
  - name: except-image
    image: exception.azurecr.io/exception:1.0.0
