apiVersion: v1
kind: Pod
metadata:
  name: nginx-users-vio2
  labels:
    app: nginx-users
spec:
  nodeSelector:
    kubernetes.io/os: linux
  securityContext:
      runAsNonRoot: true
  containers:
    - name: nginx
      image: mcr.microsoft.com/oss/nginx/nginx:1.17.3-alpine # assume non-root image, the pod will not be successfully created, but no impact on e2e result.
      securityContext:
        runAsNonRoot: false
