apiVersion: v1
kind: Pod
metadata:
  name: nginx-users-violation
  labels:
    app: nginx-users-violation
spec:
  nodeSelector:
    kubernetes.io/os: linux
  containers:
    - name: nginx
      image: mcr.microsoft.com/oss/nginx/nginx:1.17.3-alpine
      resources:
        limits:
          cpu: "100m"
          memory: "30Mi"
