apiVersion: v1
kind: Pod
metadata:
  name: nginx-apparmor-violation
  annotations:
    apparmor.security.beta.kubernetes.io/pod: unconfined
    container.apparmor.security.beta.kubernetes.io/nginx: unconfined
  labels:
    app: nginx-apparmor-violation
spec:
  nodeSelector:
    kubernetes.io/os: linux
  containers:
  - name: nginx
    image: mcr.microsoft.com/oss/nginx/nginx:1.17.3-alpine
