apiVersion: v1
kind: Service
metadata:
  name: allowed-port
spec:
  selector:
    app: service-allowed-ports
  ports:
    - port: 9999
      targetPort: 80
      nodePort: 30007
  type: NodePort
---
apiVersion: v1
kind: Service
metadata:
  name: allowed-port-range
spec:
  selector:
    app: service-allowed-ports
  ports:
    - port: 4333
      targetPort: 80
      nodePort: 30008
  type: NodePort
