apiVersion: v1
kind: Pod
metadata:
  name: nginx-no-privilege
  labels:
    app: nginx-no-privilege
spec:
  nodeSelector:
    kubernetes.io/os: linux
  containers:
  - name: nginx
    image: mcr.microsoft.com/oss/nginx/nginx:1.17.3-alpine
    securityContext:
      privileged: false