apiVersion: v1
kind: Pod
metadata:
  name: image-allow-windows-resource
spec:
  nodeSelector:
    kubernetes.io/os: windows
  containers:
  - name: container1
    image: mcr.microsoft.com/oss/nginx/nginx:1.17.3-alpine
    resources:
      limits:
        cpu: 100m
        memory: 100M
  - name: container2
    image: mcr.microsoft.com/oss/nginx/nginx:1.17.3-alpine
    resources:
      requests:
        cpu: 100m
        memory: 100M
      limits:
        cpu: 100m
        memory: 100M
  - name: container3
    image: exception.azurecr.io/exception:1.0.0
    resources:
      requests:
        cpu: 10m
        memory: 10M
      limits:
        cpu: 100m
        memory: 100M