apiVersion: v1
kind: Pod
metadata:
  name: nginx-service-account-default-violation
  labels:
    app: nginx-service-account
spec:
  containers:
  - name: nginx
    image: nginx
    resources:
      limits:
        cpu: "100m"
        memory: "30Mi"
