apiVersion: v1
kind: ServiceAccount
metadata:
  name: test-account-bad-2

---
apiVersion: v1
kind: Pod
metadata:
  name: nginx-service-account-violation-2
  labels:
    app: nginx-service-account
spec:
  serviceAccountName: test-account-bad-2
  automountServiceAccountToken: true
  containers:
  - name: nginx
    image: nginx
    resources:
      limits:
        cpu: "100m"
        memory: "30Mi"
