apiVersion: v1
kind: Pod
metadata:
  name: nanoserver-as-system-allow
spec:
  containers:
  - name: ping-loop
    image: mcr.microsoft.com/windows/nanoserver:1809
    command:
      - "ping"
      - "-t"
      - "127.0.0.1"
    securityContext:
      windowsOptions:
        runAsUserName: "SYSTEM"
  nodeSelector:
    "kubernetes.io/os": windows
