apiVersion: v1
kind: Pod
metadata:
  name: nanoserver-as-containeradmin
spec:
  securityContext:
    windowsOptions:
      runAsUserName: "ContainerAdmin"
  containers:
  - name: ping-loop
    image: exception.azurecr.io/exception:1.0.0
    command:
      - "ping"
      - "-t"
      - "127.0.0.1"
  nodeSelector:
    "kubernetes.io/os": windows