apiVersion: v1
kind: Pod
metadata:
  name: nginx-seccomp
  annotations:
    seccomp.security.alpha.kubernetes.io/pod: runtime/default
    container.seccomp.security.alpha.kubernetes.io/nginx: runtime/default
  labels:
    app: nginx-seccomp
spec:
  nodeSelector:
    kubernetes.io/os: linux
  containers:
  - name: nginx
    image: mcr.microsoft.com/oss/nginx/nginx:1.17.3-alpine
    resources:
      limits:
        cpu: "100m"
        memory: "30Mi"
