apiVersion: v1
kind: Pod
metadata:
  name: nginx-seccomp-win
  annotations:
    seccomp.security.alpha.kubernetes.io/pod: unconfined
    container.seccomp.security.alpha.kubernetes.io/nginx: unconfined
  labels:
    app: nginx-seccomp-win
spec:
  nodeSelector:
    kubernetes.io/os: windows
  containers:
  - name: windows-server
    image: mcr.microsoft.com/windows/servercore:ltsc2019
    command:
      - "powershell.exe"
      - "-command"
    args:
      - "Start-Sleep -s 1000"
