apiVersion: v1
kind: Pod
metadata:
  name: nginx-users
  labels:
    app: nginx-users
spec:
  nodeSelector:
    kubernetes.io/os: linux
  securityContext:
    supplementalGroups:
      - 150
    fsGroup: 150
  containers:
    - name: nginx
      image: mcr.microsoft.com/oss/nginx/nginx:1.17.3-alpine
      securityContext:
        runAsUser: 150
        runAsGroup: 150
      resources:
        limits:
          cpu: "100m"
          memory: "30Mi"
