apiVersion: v1
kind: Pod
metadata:
  name: nginx-host-filesystem-violation
  labels:
    app: nginx-host-filesystem-violation
spec:
  nodeSelector:
    kubernetes.io/os: linux
  containers:
  - name: nginx
    image: mcr.microsoft.com/oss/nginx/nginx:1.17.3-alpine
    volumeMounts:
    - mountPath: /cache
      name: cache-volume
      readOnly: true
    resources:
      limits:
        cpu: "100m"
        memory: "30Mi"
  volumes:
  - name: cache-volume
    hostPath:
      path: /tmp # directory location on host
