apiVersion: v1
kind: Pod
metadata:
  name: nginx-no-privilege-esclation
  labels:
    app: nginx-no-privilege-esclation
spec:
  nodeSelector:
    kubernetes.io/os: linux
  containers:
  - name: nginx
    image: mcr.microsoft.com/oss/nginx/nginx:1.17.3-alpine
    securityContext:
      allowPrivilegeEscalation: false
  - name: except-image
    image: exception.azurecr.io/exception:1.0.0
    securityContext:
      allowPrivilegeEscalation: true
  initContainers:
  - name: container-exclude
    image: mcr.microsoft.com/oss/nginx/nginx:1.17.3-alpine
    securityContext:
      allowPrivilegeEscalation: true