apiVersion: v1
kind: Pod
metadata:
  name: windows-server-privilege-esclation-win
  labels:
    app: windows-server-privilege-esclation-win
spec:
  nodeSelector:
    kubernetes.io/os: windows
  containers:
  - name: windows-server
    image: mcr.microsoft.com/windows/servercore:ltsc2019
    command:
      - "powershell.exe"
      - "-command"
    args:
      - "Start-Sleep -s 1000"
    securityContext:
      allowPrivilegeEscalation: true