apiVersion: v1
kind: Pod
metadata:
  name: container-exclude
  labels:
    app: container-allowed-ports
spec:
  nodeSelector:
    kubernetes.io/os: linux
  containers:
  - name: container-exclude
    image: mcr.microsoft.com/oss/nginx/nginx:1.17.3-alpine
    ports:
    - containerPort: 80