apiVersion: v1
kind: Pod
metadata:
  name: nginx-disallowed-probes-2
  labels:
    app: nginx-disallowed-probes
spec:
  nodeSelector:
    kubernetes.io/os: linux
  containers:
  - name: container1
    image: mcr.microsoft.com/oss/nginx/nginx:1.17.3-alpine
    livenessProbe:
      httpGet:
        path: /healthz
        port: 8080
        httpHeaders:
        - name: Custom-Header
          value: Awesome
      initialDelaySeconds: 3
      periodSeconds: 3