apiVersion: v1
kind: Pod
metadata:
  name: nginx-disallowed-probes-1
  labels:
    app: nginx-disallowed-probes
spec:
  nodeSelector:
    kubernetes.io/os: linux
  containers:
  - name: container1
    image: mcr.microsoft.com/oss/nginx/nginx:1.17.3-alpine
    readinessProbe:
      tcpSocket:
        port: 8080
      initialDelaySeconds: 5
      periodSeconds: 10
