apiVersion: v1
kind: Pod
metadata:
  name: image-disallow-2
spec:
  nodeSelector:
    kubernetes.io/os: windows
  containers:
  - name: container-vio1
    image: mcr.microsoft.com/oss/nginx/nginx:1.17.3-alpine
    resources:
      requests:
        cpu: 10m
        memory: 10M
      limits:
        cpu: 100m
        memory: 100M
