apiVersion: v1
kind: Pod
metadata:
  name: nginx-users-violation
  labels:
    app: nginx-users-violation
spec:
  nodeSelector:
    kubernetes.io/os: linux
  securityContext:
    supplementalGroups:
      - 250
    fsGroup: 250
  containers:
    - name: container-exclude
      image: mcr.microsoft.com/oss/nginx/nginx:1.17.3-alpine
      securityContext:
        runAsUser: 250
        runAsGroup: 250
    - name: except-image
      image: exception.azurecr.io/exception:1.0.0
      securityContext:
        runAsUser: 250
        runAsGroup: 250
