apiVersion: v1
kind: Pod
metadata:
  name: nginx-host-namespace
  labels:
    app: nginx-host-namespace
spec:
  hostPID: false
  hostIPC: false
  nodeSelector:
    kubernetes.io/os: linux
  containers:
  - name: nginx
    image: mcr.microsoft.com/oss/nginx/nginx:1.17.3-alpine
    resources:
      limits:
        cpu: "100m"
        memory: "30Mi"
---
apiVersion: v1
kind: Pod
metadata:
  name: nginx-host-namespace-imageexemption
  labels:
    app: nginx-host-namespace
spec:
  hostPID: true
  hostIPC: true
  nodeSelector:
    kubernetes.io/os: linux
  containers:
  - name: nginx
    image: exception.azurecr.io/exception:1.0.0
    resources:
      limits:
        cpu: "100m"
        memory: "30Mi"