apiVersion: v1
kind: Pod
metadata:
  name: windows-server-host-namespace-win
  labels:
    app: windows-server-host-namespace-win
spec:
  hostPID: true
  hostIPC: true
  nodeSelector:
    kubernetes.io/os: windows
  containers:
  - name: windows-server
    image: mcr.microsoft.com/windows/servercore:ltsc2019
    command:
      - "powershell.exe"
      - "-command"
    args:
      - "Start-Sleep -s 1000"
